In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.DataFrame([1,2,3],columns=['names'],index=[7,8,9])

names
7      1
8      2
9      3

In [ ]:
df=pd.DataFrame(np.random.randint(0,100,(3,3)),columns="A B C".split(),index="P Q R ".split())

In [ ]:
df

A   B   C
P  48  31  64
Q  99  78   7
R  89  70  71

In [ ]:
df=pd.DataFrame(np.random.randint(0,100,(6,6)),columns="A B C D E F".split(),index="P Q R S T U".split())

In [ ]:
df

A   B   C   D   E   F
P  20  36  14  39  22  62
Q   9  44  55  91  81  66
R  86  33  96   7  11  91
S  42  57  75  30  20  46
T  98   4  59  49  31  72
U  93  70  39  13  51  13

In [ ]:
df=pd.DataFrame(np.random.randint(0,100,(9,6)))

In [ ]:
data=[]
for i in range(1,10):
  data.append("student"+str(i))

In [ ]:
data

['student1',
 'student2',
 'student3',
 'student4',
 'student5',
 'student6',
 'student7',
 'student8',
 'student9']

In [ ]:
df.index=data

In [ ]:
df

0   1   2   3   4
student1   32  39   6  63  11
student2   24   6  46  38   0
student3   95  65  20   0  83
student4   98  27  90  48   8
student5   78  65   7  43  87
student6   54  98  75  46   2
student7   20  79  16  15  78
student8   84  78  40  21   9
student9   15  91  19  76  57
student10  45  37  34  15  90

In [ ]:
data=[]
for i in range(1,5):
  data.append("subject"+str(i))

In [ ]:
df.columns=data

In [ ]:
df

0   1   2   3   4   5
0  17  48  72  36   1  88
1  73  11  94  48  44  72
2  30  77  68  75  19  88
3  94  99   7  40  36  23
4  99  81  42  72  88  39
5  78  60  37  11  18  20
6  54  29   0  99  91  41
7  43  49  44   4  53  10
8   4  18  59   6  82  58

In [ ]:
df.shape

(9, 6)

In [ ]:
df.values

array([[17, 48, 72, 36,  1, 88],
       [73, 11, 94, 48, 44, 72],
       [30, 77, 68, 75, 19, 88],
       [94, 99,  7, 40, 36, 23],
       [99, 81, 42, 72, 88, 39],
       [78, 60, 37, 11, 18, 20],
       [54, 29,  0, 99, 91, 41],
       [43, 49, 44,  4, 53, 10],
       [ 4, 18, 59,  6, 82, 58]])

In [ ]:
df.iloc[:3,-3:]

3   4   5
0  36   1  88
1  48  44  72
2  75  19  88

In [ ]:
df.iloc[5,5]

np.int64(20)

In [ ]:
df

0   1   2   3   4   5
0  17  48  72  36   1  88
1  73  11  94  48  44  72
2  30  77  68  75  19  88
3  94  99   7  40  36  23
4  99  81  42  72  88  39
5  78  60  37  11  18  20
6  54  29   0  99  91  41
7  43  49  44   4  53  10
8   4  18  59   6  82  58

In [ ]:
df.iloc[0:4,0:4]

0   1   2   3
0  17  48  72  36
1  73  11  94  48
2  30  77  68  75
3  94  99   7  40

In [ ]:
df=pd.read_excel('/Sample - Superstore.xls')

In [ ]:
df.shape

(9994, 21)

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [ ]:
df[df['Segment']=='Consumer']

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2020-152156 2020-11-08 2020-11-11    Second Class   
1          2  CA-2020-152156 2020-11-08 2020-11-11    Second Class   
3          4  US-2019-108966 2019-10-11 2019-10-18  Standard Class   
4          5  US-2019-108966 2019-10-11 2019-10-18  Standard Class   
5          6  CA-2018-115812 2018-06-09 2018-06-14  Standard Class   
...      ...             ...        ...        ...             ...   
9989    9990  CA-2018-110422 2018-01-21 2018-01-23    Second Class   
9990    9991  CA-2021-121258 2021-02-26 2021-03-03  Standard Class   
9991    9992  CA-2021-121258 2021-02-26 2021-03-03  Standard Class   
9992    9993  CA-2021-121258 2021-02-26 2021-03-03  Standard Class   
9993    9994  CA-2021-119914 2021-05-04 2021-05-09    Second Class   

     Customer ID     Customer Name   Segment Country/Region             City  \
0       CG-12520       Claire Gute  Consumer  United States        Henderson   
1       CG-12520       Claire Gute  Consumer  United States        Henderson   
3       SO-20335    Sean O'Donnell  Consumer  United States  Fort Lauderdale   
4       SO-20335    Sean O'Donnell  Consumer  United States  Fort Lauderdale   
5       BH-11710   Brosina Hoffman  Consumer  United States      Los Angeles   
...          ...               ...       ...            ...              ...   
9989    TB-21400  Tom Boeckenhauer  Consumer  United States            Miami   
9990    DB-13060       Dave Brooks  Consumer  United States       Costa Mesa   
9991    DB-13060       Dave Brooks  Consumer  United States       Costa Mesa   
9992    DB-13060       Dave Brooks  Consumer  United States       Costa Mesa   
9993    CC-12220      Chris Cortes  Consumer  United States      Westminster   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...     42420.0   South  FUR-BO-10001798        Furniture    Bookcases   
1     ...     42420.0   South  FUR-CH-10000454        Furniture       Chairs   
3     ...     33311.0   South  FUR-TA-10000577        Furniture       Tables   
4     ...     33311.0   South  OFF-ST-10000760  Office Supplies      Storage   
5     ...     90032.0    West  FUR-FU-10001487        Furniture  Furnishings   
...   ...         ...     ...              ...              ...          ...   
9989  ...     33180.0   South  FUR-FU-10001889        Furniture  Furnishings   
9990  ...     92627.0    West  FUR-FU-10000747        Furniture  Furnishings   
9991  ...     92627.0    West  TEC-PH-10003645       Technology       Phones   
9992  ...     92627.0    West  OFF-PA-10004041  Office Supplies        Paper   
9993  ...     92683.0    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2   
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                        Eldon Fold 'N Roll Cart System   22.3680         2   
5     Eldon Expressions Wood and Plastic Desk Access...   48.8600         7   
...                                                 ...       ...       ...   
9989                             Ultra Door Pull Handle   25.2480         3   
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2   
9991                              Aastra 57i VoIP phone  258.5760         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
3         0.45 -383.0310  
4         0.20    2.5164  
5         0.00   14.1694  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.00   13.3200

In [ ]:
data=np.random.randint(0,10,10)

In [ ]:
data

array([8, 9, 2, 1, 4, 8, 9, 2, 9, 4])

In [ ]:
data[data<5]

array([2, 1, 4, 2, 4])

In [ ]:
df[(df['Region']=='West') & (df['Category']=='Office Supplies')]

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
2          3  CA-2020-138688 2020-06-12 2020-06-16    Second Class   
6          7  CA-2018-115812 2018-06-09 2018-06-14  Standard Class   
8          9  CA-2018-115812 2018-06-09 2018-06-14  Standard Class   
9         10  CA-2018-115812 2018-06-09 2018-06-14  Standard Class   
13        14  CA-2020-161389 2020-12-05 2020-12-10  Standard Class   
...      ...             ...        ...        ...             ...   
9977    9978  US-2020-103674 2020-12-06 2020-12-10  Standard Class   
9978    9979  US-2020-103674 2020-12-06 2020-12-10  Standard Class   
9979    9980  US-2020-103674 2020-12-06 2020-12-10  Standard Class   
9992    9993  CA-2021-121258 2021-02-26 2021-03-03  Standard Class   
9993    9994  CA-2021-119914 2021-05-04 2021-05-09    Second Class   

     Customer ID    Customer Name      Segment Country/Region         City  \
2       DV-13045  Darrin Van Huff    Corporate  United States  Los Angeles   
6       BH-11710  Brosina Hoffman     Consumer  United States  Los Angeles   
8       BH-11710  Brosina Hoffman     Consumer  United States  Los Angeles   
9       BH-11710  Brosina Hoffman     Consumer  United States  Los Angeles   
13      IM-15070     Irene Maddox     Consumer  United States      Seattle   
...          ...              ...          ...            ...          ...   
9977    AP-10720       Anne Pryor  Home Office  United States  Los Angeles   
9978    AP-10720       Anne Pryor  Home Office  United States  Los Angeles   
9979    AP-10720       Anne Pryor  Home Office  United States  Los Angeles   
9992    DB-13060      Dave Brooks     Consumer  United States   Costa Mesa   
9993    CC-12220     Chris Cortes     Consumer  United States  Westminster   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
2     ...     90036.0    West  OFF-LA-10000240  Office Supplies       Labels   
6     ...     90032.0    West  OFF-AR-10002833  Office Supplies          Art   
8     ...     90032.0    West  OFF-BI-10003910  Office Supplies      Binders   
9     ...     90032.0    West  OFF-AP-10002892  Office Supplies   Appliances   
13    ...     98103.0    West  OFF-BI-10003656  Office Supplies      Binders   
...   ...         ...     ...              ...              ...          ...   
9977  ...     90032.0    West  OFF-FA-10003467  Office Supplies    Fasteners   
9978  ...     90032.0    West  OFF-BI-10003727  Office Supplies      Binders   
9979  ...     90032.0    West  OFF-BI-10002026  Office Supplies      Binders   
9992  ...     92627.0    West  OFF-PA-10004041  Office Supplies        Paper   
9993  ...     92683.0    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name    Sales  Quantity  \
2     Self-Adhesive Address Labels for Typewriters b...   14.620         2   
6                                            Newell 322    7.280         4   
8     DXL Angle-View Binders with Locking Rings by S...   18.504         3   
9                      Belkin F5C206VTEL 6 Outlet Surge  114.900         5   
13          Fellowes PB200 Plastic Comb Binding Machine  407.976         3   
...                                                 ...      ...       ...   
9977           Alliance Big Bands Rubber Bands, 12/Pack   13.860         7   
9978  Avery Durable Slant Ring Binders With Label Ho...   13.376         4   
9979                  Ibico Recycled Linen-Style Covers  437.472        14   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160         2   

      Discount    Profit  
2          0.0    6.8714  
6          0.0    1.9656  
8          0.2    5.7825  
9          0.0   34.4700  
13         0.2  132.5922  
...        ...       ...  
9977       0.0    0.0000  
9978       0.2    4.6816  
9979       0.2  153.1152  
9992       0.0   13.3200  
9993       0.0   72.9480  

[1897

In [ ]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State                     object
Postal Code              float64
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

In [ ]:
df.select_dtypes(include='float').mean()

Postal Code    55245.233297
Sales            229.858001
Discount           0.156203
Profit            28.656896
dtype: float64

In [ ]:
df.select_dtypes(include='float').median()

Postal Code    57103.0000
Sales             54.4900
Discount           0.2000
Profit             8.6665
dtype: float64

In [ ]:
df.select_dtypes(include='float').min()

Postal Code    1040.000
Sales             0.444
Discount          0.000
Profit        -6599.978
dtype: float64

In [ ]:
df.select_dtypes(include='float').max()

Postal Code    99301.000
Sales          22638.480
Discount           0.800
Profit          8399.976
dtype: float64

In [ ]:
df.select_dtypes(include='float').std()

Postal Code    32038.715955
Sales            623.245101
Discount           0.206452
Profit           234.260108
dtype: float64

In [ ]:
df.select_dtypes(include='float').var()

Postal Code    1.026479e+09
Sales          3.884345e+05
Discount       4.262242e-02
Profit         5.487780e+04
dtype: float64

In [ ]:
df.select_dtypes(include='float').quantile(0.50)

Postal Code    57103.0000
Sales             54.4900
Discount           0.2000
Profit             8.6665
Name: 0.5, dtype: float64

In [ ]:
df.select_dtypes(include='float').quantile(0.75)

Postal Code    90008.000
Sales            209.940
Discount           0.200
Profit            29.364
Name: 0.75, dtype: float64

In [ ]:
df.select_dtypes(include='float').quantile(0.25)

Postal Code    23223.00000
Sales             17.28000
Discount           0.00000
Profit             1.72875
Name: 0.25, dtype: float64

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [ ]:
df.loc[:,["Sales","Region"]].groupby("Region").sum()

Sales
Region              
Central  501239.8908
East     678781.2400
South    391721.9050
West     725457.8245

In [ ]:
df.loc[:,["Sales","Region"]].groupby("Region").sum()

Sales
Region              
Central  501239.8908
East     678781.2400
South    391721.9050
West     725457.8245

In [ ]:
df.loc[:,["Sales","Region"]].groupby("Region").mean()

Sales
Region             
Central  215.772661
East     238.336110
South    241.803645
West     226.493233

In [ ]:
df.loc[:,["Sales","Region"]].groupby("Region").median()

Sales
Region         
Central  45.980
East     54.900
South    54.594
West     60.840

In [ ]:
df.shape

(9994, 21)