In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(0,5,(3,3))

In [ ]:
data

array([[0, 2, 4],
       [4, 4, 1],
       [3, 2, 0]])

In [ ]:
data.sum()

np.int64(20)

In [ ]:
data.sum(axis=1)

array([6, 9, 5])

In [ ]:
data.sum(axis=0)

array([7, 8, 5])

In [ ]:
data.max()

np.int64(4)

In [ ]:
data.min()

np.int64(0)

In [ ]:
data.max(axis=1)

array([4, 4, 3])

In [ ]:
data.min(axis=0)

array([0, 2, 0])

In [ ]:
data.min(axis=1)

array([0, 1, 0])

In [ ]:
data.max(axis=0)

array([4, 4, 4])

In [ ]:
data.argmax(axis=1)

array([2, 0, 0])

In [ ]:
data.argmax(axis=0)

array([1, 1, 0])

In [ ]:
data.argmin(axis=0)

array([0, 0, 2])

In [ ]:
data.argmin(axis=1)

array([0, 2, 2])

In [ ]:
data=np.random.randint(1,6,(3,3))

In [ ]:
data

array([[1, 4, 4],
       [5, 4, 2],
       [5, 1, 3]])

In [ ]:
data.sum(axis=1)

array([ 9, 11,  9])

In [ ]:
data.sum(axis=1).argmin()+1

np.int64(1)

In [ ]:
data.sum(axis=1).argmax()+1

np.int64(2)

In [ ]:
data.sum(axis=0)+1

array([12, 10, 10])

In [ ]:
data.sum(axis=0).argmax()+1

np.int64(1)

In [ ]:
data=np.random.randint(2,6,(3,5))

In [ ]:
data

array([[5, 4, 5, 2, 5],
       [5, 3, 5, 5, 2],
       [3, 5, 4, 4, 4]])

In [ ]:
data.sum(axis=0)[3:].sum()

np.int64(22)

In [ ]:
data[:,3:5].sum()

np.int64(22)

In [ ]:
data=np.random.randint(1,100,(20,20))

In [ ]:
data

array([[ 9, 62, 42, 40, 31, 48,  5, 28, 22, 87, 18,  1, 19, 79, 23, 48,
         4, 34, 82, 83],
       [94, 16,  1, 88, 64, 71, 59, 57, 82, 60, 18, 37, 14,  4, 51, 54,
        90, 70, 47, 45],
       [51, 59, 14, 70, 76, 99, 97, 78, 99, 68, 26, 21, 15, 12, 97, 15,
        31, 99, 46,  5],
       [28, 19, 39, 68, 92, 56, 54, 86, 80, 62, 86,  2, 15, 24, 72, 58,
        62, 60, 78, 15],
       [52, 41, 41, 87, 34,  1, 81, 59, 86, 55,  2, 15, 66, 32, 33, 75,
        81, 81, 11, 81],
       [86, 48, 96, 50, 82, 38, 98, 43, 57, 79, 68, 52, 69, 97, 33, 71,
        17, 67, 56,  1],
       [56, 94, 50, 11, 27, 15, 58, 33,  1, 15, 14, 62, 63,  5, 85, 35,
        46, 70, 19,  5],
       [99, 88, 80, 85, 40, 48, 99, 13, 51, 81,  8, 52, 48, 18, 32, 90,
        64, 27, 34, 12],
       [89, 76, 92, 33, 74, 31, 53,  1, 11, 66, 68, 31, 96, 98, 11, 83,
        26, 36, 15, 78],
       [67, 66, 82, 85, 26, 97, 51, 67,  3, 81, 60, 18, 77, 41, 97, 53,
        46, 98, 23, 91],
       [89, 44,  8, 70, 19, 34

In [ ]:
data.sum(axis=1)

array([ 765, 1022, 1078, 1056, 1014, 1208,  764, 1069, 1068, 1229, 1002,
       1017,  914, 1264,  820, 1271, 1090,  932, 1118, 1021])

In [ ]:
data.max()

np.int64(99)

In [ ]:
data.min()

np.int64(1)

In [ ]:
data.sum(axis=0).min()

np.int64(752)

In [ ]:
data.sum(axis=0).max()

np.int64(1221)

In [ ]:
data=np.random.randint(1,10,(5,5))

In [ ]:
data

array([[5, 4, 8, 5, 8],
       [8, 1, 1, 1, 6],
       [7, 6, 4, 7, 7],
       [4, 4, 2, 7, 8],
       [1, 9, 8, 3, 4]])

In [ ]:
data.mean()

np.float64(5.12)

In [ ]:
np.median(data)

np.float64(5.0)

In [ ]:
data

array([[5, 4, 8, 5, 8],
       [8, 1, 1, 1, 6],
       [7, 6, 4, 7, 7],
       [4, 4, 2, 7, 8],
       [1, 9, 8, 3, 4]])

In [ ]:
np.quantile(data,0.25)

np.float64(4.0)

In [ ]:
np.quantile(data,0.50)

np.float64(5.0)

In [ ]:
np.quantile(data,0.75)

np.float64(7.0)

In [ ]:
np.std(data)

np.float64(2.5348767228407776)

In [ ]:
np.var(data)

np.float64(6.425599999999999)

In [ ]:
data=np.random.randint(1,10,10)

In [ ]:
data

array([5, 1, 5, 4, 2, 4, 9, 8, 2, 8])

In [ ]:
data.mean()

np.float64(4.8)

In [ ]:
data=np.random.randint(1,10,10)

In [ ]:
data

array([2, 4, 6, 6, 3, 1, 2, 3, 5, 8])

In [ ]:
np.corrcoef(data)

np.float64(1.0)

In [ ]:
np.corrcoef(data.T)

np.float64(1.0)

In [ ]:
v1=np.arange(1,11)

In [ ]:
v2=np.arange(10,20)

In [ ]:
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.corrcoef(v1,v2)

array([[1., 1.],
       [1., 1.]])

In [ ]:
### Descriptive statistics
mean
median
max
min
std
var
range
quantile
q1
q3